name: Release

on:
  workflow_run:
    workflows: ["Windows Build"]
    branches: [master]
    types: 
      - completed

jobs:
  build:
    runs-on: 'windows-latest'
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: windows/Output/MAVProxyInstaller.zip